name: GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: |
          hugo --minify

      - name: List public folder
        run: |
          echo "Working directory: $(pwd)"
          ls -la
          if [ -d public ]; then echo 'public exists'; ls -la public || true; else echo 'public missing'; fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}